### ISSUE TITLE
Support for sql alchemy 2.0.x 

### ISSUE THREAD

**Issue by barmanroys** [googleapis/python-bigquery-sqlalchemy#1020]
Installed ```sqlalchemy-bigquery==1.9.0``` (which I believe is the latest version)? This is my first time using this library as I have never even used bigquery itself before. 

It seems dependent on ```sqlalchemy==1.4.x``` upstream when the upstream seems to have moved on to another major release with a lot of enhancements and vulnerability fixes. 

Is there a way to use this library together with an updated version of alchemy?

**Comment by Linchin** [comment]
Thank you @barmanroys for asking. Support for SQLAlchemy 2.0 is in the works, and we have several prereleases out already (latest being [v1.11.0.dev2](https://github.com/googleapis/python-bigquery-sqlalchemy/releases/tag/v1.11.0.dev2)). It would be great if you could try it out, and let us know if there are any issues! The official support is slated for end of Q1. I will close this as a duplicate of #510.

**Comment by gmdiana-db** [comment]
Will there be a release soon on this?

**Comment by CostcoFanboy** [comment]
Is there an experimental pypi where you put dev images on?

**Comment by Linchin** [comment]
Sorry for the late reply, starting [v1.11.0](https://github.com/googleapis/python-bigquery-sqlalchemy/releases/tag/v1.11.0) SQLAlchemy 2.0 is supported.
