### ISSUE TITLE
Add support for the BigQuery geography type.

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery-sqlalchemy#136]
The BQ geography type isn't supported.

It should be.  It would be great to get suggestions on how it should behave. :)

**Comment by JacobHayes** [comment]
If [GeoAlchemy](https://github.com/geoalchemy/geoalchemy2) folks would be interested in collaborating, it'd be great to have compatibility.

On the other hand, working with [GeoPandas](https://github.com/geopandas/geopandas) would be convenient, but there's already a bit of friction between the SQLAlchemy <-> Pandas worlds.

**Comment by jimfulton** [comment]
We'll soon be releasing GeoAlchemy _and_ GeoPandas support.  GeoPandas support will be added to the python-biquery client.
