### ISSUE TITLE
bigquery record type handling is incomplete

### ISSUE THREAD

**Issue by sumedhsakdeo** [googleapis/python-bigquery-sqlalchemy#17]
Two issues: @tswast  @mxmzdlv 
1. get_columns does not recurse into record type and return all the nested field names.
    -- I have a PR for this. Will post it for review. Also attached a working code here.
2. when you do a select \`abc.xyz\` from \`foobar-table\`
    -- bigquery does not like this syntax for the column name put in backtick, like here \`abc.xyz\`

Need recommendation on how to handle issue (2) as it blocks running tests and hence fix to issue (1).

Here is the diff for issue (1) which correctly returns all the column names
```
diff --git a/pybigquery/sqlalchemy_bigquery.py b/pybigquery/sqlalchemy_bigquery.py
index 071ddfd..1c31f9e 100644
--- a/pybigquery/sqlalchemy_bigquery.py
+++ b/pybigquery/sqlalchemy_bigquery.py
@@ -4,6 +4,7 @@ from __future__ import absolute_import
 from __future__ import unicode_literals

 from google.cloud.bigquery import dbapi
+from google.cloud.bigquery.schema import SchemaField
 from google.cloud import bigquery
 from google.api_core.exceptions import NotFound
 from sqlalchemy.exc import NoSuchTableError
@@ -160,9 +161,24 @@ class BigQueryDialect(DefaultDialect):
         except NoSuchTableError:
             return False

+    def _get_columns_helper(self, columns, cur_columns):
+        results = []
+        for col in columns:
+            if col.field_type == 'RECORD':
+                cur_columns.append(col)
+                results += self._get_columns_helper(col.fields, cur_columns)
+                cur_columns.pop()
+            results += [SchemaField(
+                            name='.'.join(col.name for col in cur_columns + [col]),
+                            field_type=col.field_type,
+                            mode=col.mode,
+                            description=col.description,
+                            fields=col.fields)]
+        return results
+
     def get_columns(self, connection, table_name, schema=None, **kw):
         table = self._get_table(connection, table_name, schema)
-        columns = table.schema
+        columns = self._get_columns_helper(table.schema, [])
         result = []
         for col in columns:
             try:
```

**Comment by mxmzdlv** [comment]
Thanks @sumedhsakdeo 

This is what I've came up so far: https://github.com/mxmzdlv/pybigquery/pull/18

Default SQLCompiler wraps the whole column in quotes, so I've changed the behaviour to wrap fields in the record separately, e.g. foobar-table.abx.xyz becomes `foobar-table`.`abx`.`xyz`.

One thing I am not sure about:

Currently `engine.execute(SELECT * FROM table)` will return the record as JSON and won't unpack it. The reflected select, however, will return JSON and unpack it to include each column in it.

For users in Superset this is probably a preferred approach?

**Comment by sumedhsakdeo** [comment]
Thanks for a your PR. I'll take a look. 

For JSON handling we're considering using pandas json_normalize to get dataframe.

I know @mistercrunch (who is creator of superset) has some ideas on handling this. I'll request him to add his thoughts to this question.

**Comment by tswast** [comment]
> Should we unpack the records with raw queries as well? What is the preferred output for `SELECT record FROM table` — a single column with JSON or unpacked fields?

FWIW a single column would most directly match the BigQuery API response.

> select `abc.xyz` from `foobar-table`

Selecting a nested column is a common thing to do and we should support it.

> get_columns does not recurse into record type and return all the nested field names. -- I have a PR for this. Will post it for review. Also attached a working code here.

Thanks, based on what you've provided, I think this is the correct fix to make, though we do have to be a little careful around `mode == REPEATED` on `RECORD` type fields. For those, you can't select the columns directly because Standard SQL won't flatten them the way that Legacy SQL did. Instead you have to do some [extra work to flatten the array first](https://cloud.google.com/bigquery/docs/reference/standard-sql/arrays#flattening-arrays)

Short-term, probably we should keep `mode == REPEATED` reported as a single SQLAlchemy `ARRAY` column, but we can recurse into plain `RECORD` column as you suggest.

**Comment by sumedhsakdeo** [comment]
>> Should we unpack the records with raw queries as well? What is the preferred output for SELECT record FROM table — a single column with JSON or unpacked fields?

IMO this will be a great addition. Because otherwise I need to use something like json_normalize() on the single column name JSON returned from API to get pandas dataframe. Although should this be done in pybigquery or dbapi? 

@tswast thoughts?

**Comment by sumedhsakdeo** [comment]
Would it work if the client uses raw connections to talk directly to dbapi?

**Comment by mxmzdlv** [comment]
AFAIK engine.execute goes through the DB-API directly as well — not sure how would we unpack it properly.

**Comment by mxmzdlv** [comment]
Pushed the new version to pypi.

**Comment by tswast** [comment]
I referenced this issue in https://github.com/apache/incubator-superset/issues/3253. I think rather than adjusting the adaptor / DB-API to flatten record types, superset should implement more robust JSON column handling.

**Comment by mxmzdlv** [comment]
I'll keep this issue open as we still might want to unpack records in raw queries on sqlalchemy-driver level.

**Comment by jimfulton** [comment]
@mxmzdlv let's create a new issue if we want to do more at some point.
