### ISSUE TITLE
Use of refresh token to connect.

### ISSUE THREAD

**Issue by jaythacker** [googleapis/python-bigquery-sqlalchemy#223]
is there any way to provide refresh token and connect with that? I want to provide refresh token from superset to impersonate users.

**Comment by tswast** [comment]
This is a great feature request. I imagine this is an additional parameter to the connection string URL parsing that we'd need to add.

There's some discussion here: https://github.com/googleapis/python-bigquery-sqlalchemy/issues/42

I'll close this issue as a duplicate of that.
