### ISSUE TITLE
unnest cross join

### ISSUE THREAD

**Issue by benman1** [googleapis/python-bigquery-sqlalchemy#225]
Hi. I've been looking around how to work with nested arrays, and I am struggling. I'd appreciate some help or hints.

There's an array column that contains structs.

I am trying to get something like this work: 
```sql
SELECT col.element
t2.some_col
FROM `tbl1` t1, UNNEST(t1.nested_column) as col
LEFT JOIN `tbl2` t2
ON col.element = t2.seconday_key
```

I am pretty much in the dark at this point. I've tried different things, for example
```python
query = select([
    func.unnest(tbl1.columns.nested_column).c.element,
    t2.columns.some_col
]).select_from(tbl1).alias("t1").join(
    tbl2,
    tbl2.columns.some_col == func.unnest(tbl1.nested_column).c.element,
)
```

**Comment by jlynchMicron** [comment]
Hi @benman1 , what was the solution to this?  I have this same issue.

**Comment by benman1** [comment]
You do 
```python
.select_from(
        func.unnest(column("array_column")).alias("array_column")
    )
```

And everywhere you refer to elements of `array_column` as `column("array_column.element")`
