### ISSUE TITLE
Authentication failing with following

### ISSUE THREAD

**Issue by Flexin1981** [googleapis/python-bigquery-sqlalchemy#244]
I have been trying to connect to with the following line from the docs

engine = create_engine("bigqueryurl", credentials_path='/path/to/keyfile.json')

however  I get the following

**Invalid argument(s) 'credentials_path' sent to create_engine()**

Any help would be great

**Comment by Flexin1981** [comment]
it would seem that this happens when in a docker container and pip installing the following.

sqlalchemy-bigquery


I had to install via pybigquery

to get this to work.

**Comment by jimfulton** [comment]
Please try again with `sqlalchemy-bigquery==1.0.0`.
