### ISSUE TITLE
DRY violation in `visit_column`

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery-sqlalchemy#274]
`visit_column` is duplicated so that we can quote columns differently, so support nested columns in structs:

https://github.com/googleapis/python-bigquery-sqlalchemy/commit/1418e662037babebb8a7e666ac7b9e2b22845758#

This can lead to hard to debug bugs when `visit_column` is out of date (as it is now).

We need to see if there's a better way to handle nested columns, for example by looking at how structured access is handled for other types.

**Comment by jimfulton** [comment]
What makes this worse is that `visit_column` changes across SQLAlchemy versions, so we can't just copy it.

**Comment by chalmerlowe** [comment]
Due to workload and staffing, closing.
