### ISSUE TITLE
Transaction management

### ISSUE THREAD

**Issue by nada-feki** [googleapis/python-bigquery-sqlalchemy#309]
Hi,

Is it possible to have transaction management ? (begin, commit, rollback)
https://cloud.google.com/bigquery/docs/reference/standard-sql/transactions?hl=fr

Thanks.
Nada

**Comment by jimfulton** [comment]
> Is it possible to have transaction management ? (begin, commit, rollback)
> https://cloud.google.com/bigquery/docs/reference/standard-sql/transactions?hl=fr

No, because SQLAlchemy (+ sqlalchemy-bigquery) has no way to use BigQuery scripts.
