### ISSUE TITLE
maybe be less back-quotey, or at least simplify quoting logic

### ISSUE THREAD

**Issue by jimfulton** [googleapis/python-bigquery-sqlalchemy#337]
The existing implementation back-quotes everything. It's not clear why.  Possibly it's to avoid maintaining a list of keywords.  This has led to some code complexity, especially around column names, which can't contain funky characters even when back-quoted. Back-quoting _is_ needed if columns names conflict with identifiers.

Also, it turns out that dots aren't allowed in table names. See:
https://issuetracker.google.com/issues/199114438

This might allow us to simplify quoting rules.

**Comment by chalmerlowe** [comment]
Closing as "won't fix"
