### ISSUE TITLE
Support Base.metadata.create_all for STRUCT and ARRAY data types

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-sqlalchemy#37]
Follow-up to https://github.com/mxmzdlv/pybigquery/issues/31

**Comment by micimize** [comment]
Possibly useful for reference:
* [sqlalchemy's postgres ARRAY type](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/array.py#L152)
* [sqlalchemy's postgres JSON type](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/json.py#L102)
