### ISSUE TITLE
Python 3.10 support 

### ISSUE THREAD

**Issue by rkashapov** [googleapis/python-bigquery-sqlalchemy#374]
Hello!

It would be great to get python 3.10 supported by this excellent package.

Thanks,
Rustam

**Comment by tswast** [comment]
Thanks for the request!

This will require some investigation. Current Python 3.10 tests fail with

```
ERROR: No matching distribution found for Fiona==1.8.20
```

https://source.cloud.google.com/results/invocations/5f015b38-5fa3-4c33-9d7e-729756858ac5/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-bigquery-sqlalchemy%2Fsamples%2Fpython3.10%2Fcontinuous/log

**Comment by aucampia** [comment]
@tswast Is there a reason the versions in here are hard-coded?

- https://github.com/googleapis/python-bigquery-sqlalchemy/blob/6e2fa4925b5407c9d7d66f5840d51e9bf44f5008/samples/snippets/requirements.txt
- https://github.com/googleapis/python-bigquery-sqlalchemy/blob/6e2fa4925b5407c9d7d66f5840d51e9bf44f5008/samples/snippets/requirements-test.txt

I'm thinking of just making a patch to add `requirements.in` and `requirements-test.in` and then use `pip-compile` on those, any objections to this?

**Comment by aucampia** [comment]
And just to clarify, if this is blocked because `Fiona==1.8.20` does not support python 3.10 then it will never unblock because pypi version should be immutable, so ideally it should be `Fiona` in general, and the right way to then vary that is with pip-compile I think (or something more advanced).

**Comment by aucampia** [comment]
I'm unclear on what Fiona was for, but test seem to pass for 3.10 if I make a requirements.txt from a sane requirements.in
