### ISSUE TITLE
Table creation partition/cluster support

### ISSUE THREAD

**Issue by jlynchMicron** [googleapis/python-bigquery-sqlalchemy#395]
**Is your feature request related to a problem? Please describe.**
Quickly looking through the source code, it looks like there is no support for partition/cluster configuration at time of table creation.  The best reference I see anywhere close to this is in the function base.py -> get_indexes.  So it looks like we can just get indexing information but not set indexing.

 **Describe the solution you'd like**
Added support for index configuration.

 **Describe alternatives you've considered**
Will probably need to make another SQL query to check metadata if indexing is in place, and if not, set the indexing via SQLalchemy text() function.

**Comment by pykenny** [comment]
I think one of the challenges is that current DDL only supports defining clustering/partitioning on table creation, but doesn't support altering them afterwards. So I'm not sure if overriding `Index` class would work, or we should add a new class such as `Clustering` and `Partitioning` instead.

[Current API](https://cloud.google.com/bigquery/docs/creating-clustered-tables#modifying-cluster-spec) allows modifying clustering settings in-place, but not for partitioning.

Also there are several constraints compared to regular relational DB:
 * At most one clusterings/partitioning is allowed per table
 * Only top-level columns and specific data types are supported
 * Clustering has limit on number of columns for multi-column sorting (4 columns for now)
 * Partitioning can only specify 1 column
 * Optional filtering requirement on partitioned column

**Comment by jlynchMicron** [comment]
Thanks @chalmerlowe !!!

**Comment by chalmerlowe** [comment]
Thank @nlenepveu 
They did all the heavy lifting.
