### ISSUE TITLE
Filtering based on _PARTITIONTIME column

### ISSUE THREAD

**Issue by C0rine** [googleapis/python-bigquery-sqlalchemy#40]
I'm not sure if this is supported, but I could not get it to work. I'm trying to filter a query based on a `_PARTITIONTIME` column (e.g. in SQL: `WHERE _PARTITIONTIME >= '2019-01-01'
    AND _PARTITIONTIME < '2019-02-01'`).

I've tried `table.c._PARTITIONTIME.between(..., ...)` and using `literal(_PARTITIONTIME) >= ...`, but both are not working.

**Comment by jimfulton** [comment]
You can't use `c`.  You have to use `sqlalchemy.column`, as in:

```
conn.execute(select([t]).where(column('_partitiondate') > datetime.date(2021, 5, 24)))
```

or even:

```
conn.execute(select([t.c.x, column('_partitiondate').label('ptime')]).where(column('_partitiondate') > datetime.date(2021, 5, 24)))
```

@C0rine does this work for you?
