### ISSUE TITLE
New trailing precision zeros are introduced for float and decimal. How to 'normalize' decimal values using a sql alchemy? 

### ISSUE THREAD

**Issue by ievgennaida** [googleapis/python-bigquery-sqlalchemy#473]
after the migration from 
pybigquery
google-cloud-bigquery         2.32.0

To:
google-cloud-bigquery         3.2.0
google-cloud-bigquery-storage 2.14.1

All decimal table values are retuned with extra trailing zeros 0 after the coma.

Before:
Column debug log:
Decimal('40')

Now:
Column value debug log:
Decimal('40.000000000')

Problem: 

In the DB **40** is stored. I would expect string column to receive exact "40" not "40.000000000".

#### Environment details

  - OS type and version: Windows
  - Python version: `Python 3.8.10`
  - pip version: `pip 22.1.2`
  - google-cloud-bigquery         3.2.0
  - google-cloud-bigquery-storage 2.14.1
  - SQLAlchemy==1.3.24
  - Also tested with SQLAlchemy==1.4.39
  
#### Steps to reproduce

  1. Create table with the decimal column.
  2. Fetch table value the biqquery using the specified libs.

Thank you

**Comment by chalmerlowe** [comment]
Due to workloads and priorities, closing.

**Comment by ievgennaida** [comment]
@chalmerlowe issue is not solved, why to close it?
