### ISSUE TITLE
Support recent PyArrow versions

### ISSUE THREAD

**Issue by willsthompson** [googleapis/python-bigquery-sqlalchemy#478]
**Is your feature request related to a problem? Please describe.**

This package's [pyarrow requirement](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/main/setup.py#L88) is effectively pinned to 6.0.1, which was released almost 9 months ago. This is preventing us from upgrading to new versions of other packages requiring more recent versions of pyarrow. e.g. the latest snowflake-connector-python requires pyarrow 8.

 **Describe the solution you'd like**

Bump your pyarrow requirement to support as many and as recent versions as possible.

 **Describe alternatives you've considered**

Right now we're waiting to upgrade packages with conflicting pyarrow dependencies, but we're considering pinning pyarrow to a newer version and testing to see if this package still works (for our implementation, at least)

**Comment by woidda** [comment]
See also the discussion here https://github.com/googleapis/python-bigquery-sqlalchemy/issues/385
