### ISSUE TITLE
Only read support?

### ISSUE THREAD

**Issue by robyinno** [googleapis/python-bigquery-sqlalchemy#5]
But actually have only read support?

**Comment by mxmzdlv** [comment]
I've just pushed an update that fixes an issue with DML statements, so they should work properly now. I haven't tested them extensively, but seem to pass basic tests.

**Comment by jimfulton** [comment]
@robyinno I'm not sure what the issue is, but did @mxmzdlv's changes address the problem?

If not, can you provide more specifics of what you want to do and can't?

**Comment by robyinno** [comment]
Sorry I have forget to answer,
In fact is passed a long time so now I'm directly focused in other task,
sorry.
Roberto

Il giorno ven 30 lug 2021 alle ore 05:40 meredithslota <
***@***.***> ha scritto:
