### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by Tenzer** [googleapis/python-bigquery-sqlalchemy#500]
**Is your feature request related to a problem? Please describe.**
This package currently specifies it isn't compatible with Python 3.11 (released yesterday), blocking me from upgrading to the latest stable Python release:
https://github.com/googleapis/python-bigquery-sqlalchemy/blob/f1889443bd4d680550387b9bb14daeea8eb792d4/setup.py#L98

 **Describe the solution you'd like**
Ideally, the upper bound should either be removed, or perhaps be set to `<4.0.0` so this won't become a problem for each new minor Python release.

 **Describe alternatives you've considered**

 **Additional context**
I don't know the background for why the upper boundary is set to 3.10, so perhaps this will just be a matter of either removing the upper boundary or setting it to e.g. `4.0`.

**Comment by potiuk** [comment]
Yeah. Would be cool. We also need it for Apache Airflow. I keep on rebasing https://github.com/apache/airflow/pull/27264 and right now 3.11 stay is way better than it was when I started a month ago (PyArrow just released binary wheels two days ago and it unblocked our CI builds - there are a couple more for Google integration and bigquery sqlalchemy is on the list too.

If there is any way I can help - happy to help!
