### ISSUE TITLE
Dry run queries fail with 404:Not found job

### ISSUE THREAD

**Issue by diego-serrano-glean** [googleapis/python-bigquery-sqlalchemy#56]
While using the library to execute a query in dry run mode, I got an error like the following: `404 GET https://bigquery.googleapis.com/bigquery/v2/projects/MYDATASET/queries/None?maxResults=0&location=US: Not found: Job MYDATASET:US.None`

The code I used to execute the query is:
```
from pybigquery.api import ApiClient

credentials_info = {
  "type": "...",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "...",
  "client_email": "...",
  "client_id": "...",
  "auth_uri": "...",
  "token_uri": "...",
  "auth_provider_x509_cert_url": "...",
  "client_x509_cert_url": "..."
}

engine = create_engine('bigquery:///MYDATASET?dry_run=true', credentials_info=credentials_info)
query = 'SELECT column1 FROM `myschema`.`mytable` LIMIT 1'

try:
    with engine.connect() as conn:
      results = conn.execute(query)
```

When I execute the query with an engine that does not specify the dry run (e.g. `engine = create_engine('bigquery:///MYDATASET', credentials_info=credentials_info)`), the results are returned correctly.

Am I missing some parameters or special configuration for dry run queries?

**Comment by tswast** [comment]
Is your goal just to check query syntax with this dry run configuration? Would you expect `conn.execute` to return an empty list?

I suspect this is an issue with the underlying [DB-API](https://googleapis.dev/python/bigquery/latest/dbapi.html).

```
from google.cloud import bigquery
from google.cloud.bigquery import dbapi

query_config = bigquery.QueryJobConfig(dry_run=True)
client = bigquery.Client(default_query_job_config=query_config)
conn = dbapi.connect(client=client)
cur = conn.cursor()

# This line fails with "404 job not found" when in dry_run mode.
cur.execute(
    """
    SELECT country_name
    FROM `bigquery-public-data.utility_us.country_code_iso`
    WHERE country_name LIKE 'U%'
    """
)

results = cur.fetchall()
print(results)
```

Fails with:

```
$ python try_dbapi.py
Traceback (most recent call last):
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 175, in execute
    self._query_job.result()
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/google/cloud/bigquery/job.py", line 3210, in result
    timeout=timeout,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 1287, in _get_query_results
    retry, method="GET", path=path, query_params=extra_params, timeout=timeout
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 556, in _call_api
    return call()
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/swast/miniconda3/envs/scratch/lib/python3.7/site-packages/google/cloud/_http.py", line 423, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/swast-scratch/queries/None?maxResults=0&location=US: Not found: Job swast-scratch:US.None
```

@diego-serrano-glean Would you mind filing a feature request over at https://github.com/googleapis/python-bigquery/issues ?

**Comment by diego-serrano-glean** [comment]
My goal is to check query syntax, and optionally get some stats, namely show the total bytes processed.  Is that something I can do with pybigquery?

The issue was filed at https://github.com/googleapis/python-bigquery/issues/118

**Comment by tswast** [comment]
I'm not aware of anywhere that pybigquery exposes the job stats such as total bytes processed. Is that something you've seen in other SQLAlchemy connectors?

**Comment by diego-serrano-glean** [comment]
Checking the syntax would be enough.  Is that available in pybigquery?

**Comment by tswast** [comment]
The underlying DB-API throws an exception on bad syntax. The same is true of pybigquery.

**Comment by tswast** [comment]
Closing, as I believe this has been fixed by the change to `google-cloud-bigquery`.
