### ISSUE TITLE
Alembic support

### ISSUE THREAD

**Issue by MCFHTAGENTS** [googleapis/python-bigquery-sqlalchemy#65]
Hi,
Would you consider adding support for Alembic?
See here for details and a suggested implementation:
https://github.com/sqlalchemy/alembic/issues/738
Thanks
Mark

**Comment by mvoitko** [comment]
@mxmzdlv Can you help me with https://github.com/mxmzdlv/pybigquery/pull/70?

**Comment by MCFHTAGENTS** [comment]
It looks like you can’t do alter tables
Only drop and recreate sigh...

**Comment by jimfulton** [comment]
You can d alter table. https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_add_column_statement

Maybe this was added in the last few months. :man_shrugging:

**Comment by jimfulton** [comment]
Alembic support was released in 0.9.0.
