### ISSUE TITLE
Handling NULL dates

### ISSUE THREAD

**Issue by MCFHTAGENTS** [googleapis/python-bigquery-sqlalchemy#66]
Hi,
I have a bigquery table with a nullable DATE field.
I set the field to `None` and get the following error when I try and insert the record

`sqlalchemy.exc.ProgrammingError: (google.cloud.bigquery.dbapi.exceptions.ProgrammingError) encountered parameter end_date with value None of unexpected type`

Please can you have a look at Null handling in your stack

Also, and this may be better tracked as a separate issue when a pandas datetime is stored in a DATE  column you don't detect the need to cast the result

Thanks
Mark

**Comment by jeremy-ecoenergy** [comment]
I ran into this too. I ended up removing/not adding the column value for a given row when the value is None, and it seems to work fine. Eg if you’re using a dict, remove the key for the NULL value.

**Comment by hoanghiep106** [comment]
I also ran into this. But `sqlalchemy.null()` saved my life.
