### ISSUE TITLE
Implement listing of models

### ISSUE THREAD

**Issue by romainr** [googleapis/python-bigquery-sqlalchemy#68]
https://cloud.google.com/bigquery-ml/docs/listing-models#listing_models

`In the navigation panel, in the Resources section, click your project name.

As you expand each of the datasets in a project, models are listed along with the other BigQuery resources in the datasets. Models are indicated by the model icon: model icon`

Maybe initially would be a first step to return them in the get_table_names()?

**Comment by romainr** [comment]
So far could not find a way to prefix them with `'model#.'` and return them in `get_table_names()`

**Comment by jimfulton** [comment]
Maybe I'm missing something, but models aren't like tables.  How would you expect them to work with SQLAlchemy?

I assume you're aware that you can list models using the BigQuery client library.
