### ISSUE TITLE
pyarrow dependency should be optional

### ISSUE THREAD

**Issue by twm** [googleapis/python-bigquery-sqlalchemy#743]
pyarrow is an [optional dependency](https://github.com/googleapis/python-bigquery/blob/204779c57e706c002ababff72f8e45f1e376b960/setup.py#L31-L69) of google-cloud-bigquery, but it's [made mandatory](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/a3b8a5f0bbea79b11d5390aef547cfd87bb5808c/setup.py#L90) by python-bigquery-sqlalchemy.

As pyarrow is quite large on disk &mdash; 100 MB on x86_64 Linux &mdash; I don't want to install it when it's unused in my application (AFAICT I don't need `google-cloud-bigquery-storage` either but that's [not huge](https://pypi.org/project/google-cloud-bigquery-storage/#files)).

I suggest:

1. Removing the direct dependencies on `pyarrow` and `google-cloud-bigquery-storage`
2. Add a `bqstorage` extra that depends on `google-cloud-bigquery[bqstorage]`. That'll respect upstream's version bounds without introducing local bounds that could cause conflicts for users.
3. Document that users wanting improved performance with large result sets should install `bigquery-sqlalchemy[bqstorage]`.

There's an existing PR at #470 but it looks like it has stalled out, so I'm filing this issue to provide a blueprint for someone who's able to do this work.

**Comment by shollyman** [comment]
marking as a packaging-related issue for now, pending someone picking this up

**Comment by chalmerlowe** [comment]
@twm Thanks for creating this issue. Your suggestions were much appreciated and helped us move the ball down the field.
`pyarrow` and `bqstorage` should both be optional in the next release.

**Comment by jlynchMicron** [comment]
Hi All,

Now that bqstorage is an optional dependency, how does one specify using it (other than installing the dependencies)? If you install "sqlalchemy-bigquery[bqstorage]", will all queries automatically be ran with the bqstorage API?  From browsing around the code, my guess is no and this issue (https://github.com/googleapis/python-bigquery/issues/757) mentions it now possibly being a no-op.

At this point, is bqstorage support completely dropped from sqlalchemy-bigquery?

**Comment by parthea** [comment]
Hi @jlynchMicron,
Please could you open a new issue with your question? 

cc @chalmerlowe
