### ISSUE TITLE
Add support for BigQuery ML SQL function calls

### ISSUE THREAD

**Issue by jlynchMicron** [googleapis/python-bigquery-sqlalchemy#746]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
No.

 **Describe the solution you'd like**
Add support for BigQuery ML SQL function calls.

 **Describe alternatives you've considered**
Hard coding SQL query strings.

**Comment by shollyman** [comment]
unclear currently how deeply we want to track all the ML.* functions, TVFs, etc.  Marking as P3 for now.

**Comment by chalmerlowe** [comment]
Due to our existing workload and staffing and the existence of workarounds (as noted in the ticket) going to mark this as will not fix and close this request.
