### ISSUE TITLE
How can I suppress the UserWarning?

### ISSUE THREAD

**Issue by caffeinatedMike** [googleapis/python-bigquery-sqlalchemy#80]
I keep seeing a `UserWarning` printed in my logs about not being able to create a BigQuery Storage Client. 
```
2021-02-03 12:49:45 [py.warnings] WARNING: c:\users\mhill\pycharmprojects\scrapy\venv\lib\site-packages\google\cloud\bigquery\client.py:441: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  "Cannot create BigQuery Storage client, the dependency "
```
How can I prevent this from showing up in the logs since it does not effect the functionality?

**Comment by alonme** [comment]
@caffeinatedMike 

This warning is actually raised by https://github.com/googleapis/python-bigquery
The storage client is very useful, so i generally think this warning is in place.

Check out the python docs regarding filtering errors https://docs.python.org/3/library/warnings.html#warnings.filterwarnings

and a usage example https://stackoverflow.com/questions/9134795/how-to-get-rid-of-specific-warning-messages-in-python-while-keeping-all-other-wa

**Comment by caffeinatedMike** [comment]
Thanks for the heads-up @alonme. I knew about `warnings.filterwarnings`, I was just getting inconsistent results when using it to surpress the python-bigquery warning. Basically, I have a `models.py` which, along with db model declarations, includes a few functions to pull down data from bigquery and create a temporary staging database for isolated vm instances (reducing memory and storage needs per instance). 

I used to have the following at the top of the file:
```python
# sqlalchemy-related imports are above warnings import
import warnings
warnings.filterwarnings("ignore", message=r"UserWarning: Cannot create BigQuery Storage client")
```

With the above, I was noticing the warning still being printed in some situations when the functions were imported and invoked from other files throughout the project. Maybe it's due to the message parameter not accurately catching everything according to the regex?

Regardless, I now have the following at the top of the file:
```python3
# sqlalchemy-related imports are above warnings import
import warnings
warnings.filterwarnings('ignore', category=UserWarning)
```
Hopefully this will resolve the intermittent messages

**Comment by jimfulton** [comment]
I think this question was answered. :)
