### ISSUE TITLE
New google-cloud-bigquery dependency versions not supported

### ISSUE THREAD

**Issue by pedro-iatzky** [googleapis/python-bigquery-sqlalchemy#81]
## Problem
With the new google-cloud-bigquery dependency versions, I keep getting `None` as a result for every query I run.

## How to reproduce
I have tested with the code of the very first example of the readme:
```
from sqlalchemy import *
from sqlalchemy.engine import create_engine
from sqlalchemy.schema import *
engine = create_engine('bigquery://project')
table = Table('dataset.users', MetaData(bind=engine), autoload=True)
print(select([func.count('*')], from_obj=table).scalar())
```

For this combination of dependencies:
```
google-cloud-bigquery==2.8.0
pybigquery==0.5.0
```
Result: `None`

For this other combination of dependencies:
```
google-cloud-bigquery==1.24.0
pybigquery==0.5.0
```
Result: `10`

**Comment by tswast** [comment]
@pedro-iatzky Do you have the BigQuery Storage API enabled?
