### ISSUE TITLE
Inspect dataset and query jobs in different projects

### ISSUE THREAD

**Issue by farnsworth** [googleapis/python-bigquery-sqlalchemy#835]
To inspect `bigquery-public-data.baseball` I would do:
```
eng = create_engine("bigquery://bigquery-public-data/baseball")
inspect(eng)
```
However, with the same engine you can't submit any query, because the user does not have bigquery.jobs.create permission in project bigquery-public-data.

Maybe, it could be useful to optionally indicate two projects in the URL, one to indicate where jobs should be submitted, and one to indicate the project dataset. With something similar to this:
```
create_engine("bigquery://job_project/bigquery-public-data.baseball")
```
or this:
```
create_engine("bigquery://bigquery-public-data/baseball?job_project_id=job_project")
```

Am I missing something?

**Comment by chalmerlowe** [comment]
This seems like it is an edge case and one that could be resolved by using one engine to perform the inspection and then creating a new/separate engine to do queries and other work.

Based on our current workload and existing priorities, this feature request will not be implemented.
