### ISSUE TITLE
getting all the users/groups/service account who has access to a table and columns they have access to in that table

### ISSUE THREAD

**Issue by Opperessor** [googleapis/python-bigquery-sqlalchemy#848]

**Comment by shollyman** [comment]
Resolving all identities who have access isn't an aspect of the API, so this isn't something one should expect to be exposed here.

The closest alternative I can suggest is querying INFORMATION_SCHEMA, particularly OBJECT_PRIVILEGES:

https://cloud.google.com/bigquery/docs/information-schema-object-privileges
