### ISSUE TITLE
Allow to set a timeout on query

### ISSUE THREAD

**Issue by maingoh** [googleapis/python-bigquery-sqlalchemy#849]
**Is your feature request related to a problem? Please describe.**

I have some queries which seem to hang, but when retried a second time works. 

 **Describe the solution you'd like**

It would be nice to be able to set timeout at each query so that we can retry quickly, maybe through `execution_options` of sqlalchemy or at the engine level at least.

 **Describe alternatives you've considered**

I have tried hacking the bigquery client but couldn't make it work:
```python
with engine.begin() as connection:
    connection.connection._client._default_query_job_config.script_options = ScriptOptions(statement_timeout_ms=10)
    connection.execute(...)
```
This is probably not the options I would like, I think the timeout probably needs to be set here https://github.com/googleapis/python-bigquery/blob/5d0ebf462e49cb7aea474c9de3a8c2ea4fa11c58/google/cloud/bigquery/dbapi/cursor.py#L213

**Comment by chalmerlowe** [comment]
@maingoh 

This might be what you are looking for:

There is an ability to set a default retry on some methods:
https://github.com/googleapis/python-bigquery/blob/41799b4d22101bef8d3b00b52759a2390e7c624d/google/cloud/bigquery/retry.py#L53

```
Any method with a ``retry`` parameter will be retried automatically,
with reasonable defaults. To disable retry, pass ``retry=None``.
To modify the default retry behavior, call a ``with_XXX`` method
on ``DEFAULT_RETRY``. For example, to change the deadline to 30 seconds,
pass ``retry=bigquery.DEFAULT_RETRY.with_deadline(30)``.
```

Relatedly there is the ability to set a default timeout on some methods:

https://github.com/googleapis/python-bigquery/blob/41799b4d22101bef8d3b00b52759a2390e7c624d/google/cloud/bigquery/retry.py#L63

Timeout and Retry are two different limitations. Please be sure to read the function docstrings to be clear on how/when they are used.

Re: retry, many functions in the library have the ability to tweak the retry values. IF you do a find on `retry` in the `query.py` file, for example, you will see that a number of aspects of a query can be refined.
https://github.com/googleapis/python-bigquery/blob/41799b4d22101bef8d3b00b52759a2390e7c624d/google/cloud/bigquery/job/query.py

**Comment by chalmerlowe** [comment]
There has been no response to the latest comment.
Closing this issue.
