### ISSUE TITLE
base.metadata.create_all does not work ocasionally.

### ISSUE THREAD

**Issue by todhm** [googleapis/python-bigquery-sqlalchemy#893]
#### Environment details
- Python 3.10.12
Name: sqlalchemy-bigquery
Version: 1.7.0
Summary: SQLAlchemy dialect for BigQuery
Home-page: https://github.com/googleapis/python-bigquery-sqlalchemy
Author: The Sqlalchemy-Bigquery Authors
Author-email: googleapis-packages@google.com
License: 
Location: /usr/local/lib/python3.10/site-packages
Requires: google-a
#### Steps to reproduce

  1. I'm trying to use base.metadata.create_all to run pytest on bigquery. but ocasionally it stopped without  any reason with following error . 'Connection to bigquery.googleapis.com timed out. (connect timeout=None)'))

#### Code example

```
import pytest
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()

test_engine = create_engine(TestConfig.BIGQUERY_URL, SessionTest = sessionmaker(autocommit=False, autoflush=False, bind=test_engine)

@pytest.fixture
def test_session() -> sessionmaker:
    Base.metadata.create_all(test_engine)
    yield get_test_session()
```

**Comment by chalmerlowe** [comment]
I am not sure there is enough detail here to debug this issue. Closing.
IF you are able to provide more context regarding this issue it may be possible to assist with debugging efforts.
